#!/bin/bash

music="/home/steven/Music"
playlist="/home/steven/Music/playlist"
find $music  -type f -iregex ".*\.\(aac\|flac\|mp3\|ogg\|wav\)$" | sort > $playlist
#find -maxdepth 1 -type f -iregex ".*\.\(aac\|flac\|mp3\|ogg\|wav\)$" | sort > playlist
keyword=$1
if [ -z "$keyword" ]
then
	mplayer -shuffle -really-quiet -playlist $playlist & 
	exit
else
	pl=`cat $playlist | grep -i $1`
	mplayer -shuffle -really-quiet $pl 
fi
